float IngresarKilometros(void);
float IngresarPreciosVuelos(void);
float ValidarNumero(float,float,char[]);
float CalcularcostosDebito(float);
float CalcularCostosCredito(float);
float CalcularCostosBtc(float);
float CalcularPrecioPorKilometro(float);
float CalcularPrecioUnitario(float, float);
float CalcularDiferenciaPrecio(float, float);
void MostrarResultados(float,float,float,float);
